name: Deploy to OpenShift (dev)

on:
  push:
    branches:
      - deploy-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install oc CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true

      - name: Trigger build
        run: |
          oc start-build news-build -n atv-mc-newsletter-build --wait --follow
